dataset:
  name: PDE_KS
  pair_id: 'all'
model:
  name: SINDy
  POD_modes: 20
  differentiation_method: 'finite_difference'
  differentiation_method_order: 2
  feature_library: 'polynomial'
  feature_library_order: 5
  optimizer: 'STLSQ'
  threshold: 0.0001
  alpha: 0.05
