dataset:
  name: PDE_KS
  pair_id: [4]
model:
  POD_modes: 5
  alpha: 10.0
  differentiation_method: finite_difference
  differentiation_method_order: 5
  feature_library: polynomial
  feature_library_order: 2
  name: SINDy
  optimizer: FROLS
  threshold: 50.0